version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev # path to Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # ignore
      - .:/app # local:container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]