version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev # path to Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # ignore
      - .:/app # local:container
